### ISSUE TITLE
Navbar white couleur

### ISSUE THREAD

**Issue by michellecarrasco** [michellecarrasco/thomas-lammens#1]
Navbar :
Texte de couleur bleue #1779ba  au lieu de white
Essaie : 
Gros mystère -  je vois la couleur dans le code quand je fais cmd+alt+c.
Si je décoche la couleur le texte apparait en violet. 

Ni la couleur bleu ni la violette n'est pas présente dans mon vrai code.

**Comment by michellecarrasco** [comment]
Idem pour Navbar black : 
Avant en hover le text se mettait noir là il ne réagit plus. 

Il n'y a que l'effet de ligne qui apparait qui fonctionne

**Comment by gnuletik** [comment]
See #3
